### PR TITLE
Update en.yml , reminder subject 

### PR DESCRIPTION
**Pull request by enginegrid**
Updating to meal reminder email,  line 444
updating subject line to move "date/time" to the left, to improve visibility in mobile email application.

### CODE REVIEW

**Review by smoyte — COMMENTED** [review]
Could you please paste some example subjects before and after the change? Also it seems the tests didn’t run, perhaps because it’s your own clone. I will look into this later

**Comment by enginegrid** [comment]
Before:
Meal Reminder: Peanut Sesame Noodles on Wed Sep 13 6:15pm at GO CH


After (expected):
Meal Reminder: Wed Sep 13 6:15pm - Peanut Sesame Noodles at GO CH

**Comment by smoyte** [comment]
@enginegrid the change looks good, but I want to make sure it doesn't break any tests.

For some reason the tests didn't run on this PR. Perhaps b/c it came from your clone?

Are you able to clone the to push your branch to the main repo?

```
git checkout your_branch
git remote add main git@github.com:gather-community/gather.git
git push main
```

**Comment by enginegrid** [comment]
Added a branch "alex_branch"
and pushed it up

**Pull request closed without merging**
